# Generated by Django 5.1.4 on 2025-01-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='reference_no',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
