# Generated by Django 5.1.5 on 2025-01-16 07:40

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneAPI', '0002_schedule_reference_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('separated', 'Separated'), ('widowed', 'Widowed'), ('in_a_civil_partnership', 'In a civil partnership')], default='single', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='PH', unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
