# Generated by Django 5.1.1 on 2024-10-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneAPI', '0006_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='pending', max_length=10),
        ),
    ]
