# Generated by Django 5.1.1 on 2024-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneAPI', '0008_customuser_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-date', 'timeslot']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='status_history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
