name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      # - name: Run tests

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/app || git clone https://github.com/jetarciaga/capstone-backend.git /home/ubuntu/app
            cd /home/ubuntu/app

            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" > .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" > .env
            echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" > .env
            echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" > .env
            echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > .env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" > .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > .env
            echo "AWS_REGION_NAME=${{ secrets.AWS_REGION_NAME }}" > .env
            echo "AWS_SES_REGION_ENDPOINT=${{ secrets.AWS_SES_REGION_ENDPOINT }}" > .env
            echo "DEFAULT_FROM_EMAIL=${{ secrets.DEFAULT_FROM_EMAIL }}" > .env

            git pull origin main
            docker-compose down --volumes
            docker-compose up --build -d
